# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todo2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton
conn=sqlite3.connect('mylist.db')
#create a cursor
c=conn.cursor()
#create table
c.execute("""CREATE TABLE if not exists todo_list(list_item text)""")
conn.commit()
conn.close()
class Ui_MainWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(417, 370)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_item_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.add_it())
        self.add_item_button.setGeometry(QtCore.QRect(20, 50, 111, 23))
        self.add_item_button.setObjectName("add_item_button")
        self.del_item_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.delete_it())
        self.del_item_button.setGeometry(QtCore.QRect(150, 50, 75, 23))
        self.del_item_button.setObjectName("del_item_button")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.clear_it())
        self.clear_button.setGeometry(QtCore.QRect(230, 50, 75, 23))
        self.clear_button.setObjectName("clear_button")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 341, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(60, 90, 331, 192))
        self.listWidget.setObjectName("listWidget")
        self.save_data = QtWidgets.QPushButton(self.centralwidget,clicked=lambda:self.save_it())
        self.save_data.setGeometry(QtCore.QRect(300, 50, 101, 23))
        self.save_data.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 417, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        #grab items from db
        self.grab_all()
    def grab_all(self):
        conn = sqlite3.connect('mylist.db')
        # create a cursor
        c = conn.cursor()
        # create table
        c.execute("SELECT * FROM todo_list")
        records=c.fetchall()

        conn.commit()
        conn.close()
        #loop thru records
        for record in records:
            self.listWidget.addItem(str(record[0]))
    def add_it(self):
        item=self.lineEdit.text()
        #add it to list

        self.listWidget.addItem(item)
        #clear the text box
        self.lineEdit.setText("")
    def delete_it(self):
        #grab current row
        clicked=self.listWidget.currentRow()
        #delete row
        self.listWidget.takeItem(clicked)
    def clear_it(self):
        self.listWidget.clear()
    def save_it(self):
        conn = sqlite3.connect('mylist.db')
        # create a cursor
        c = conn.cursor()

        #Delete Everything in the database table
        c.execute('DELETE FROM todo_list;',)
        # create table
        c.execute("SELECT * FROM todo_list")
        records = c.fetchall()

        items=[]
        for index in range(self.listWidget.count()):
            items.append(self.listWidget.item(index))
        for item in items:
            c.execute("INSERT INTO todo_list VALUES (:item)",{'item': item.text(),})

            print(item.text())
        conn.commit()
        conn.close()
        msg=QMessageBox()
        msg.setWindowTitle("Saved to database")
        msg.setText('Your TodoList has been saved')
        msg.setIcon(QMessageBox.Information)
        msg.exec_()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "To Do List"))
        self.add_item_button.setText(_translate("MainWindow", "Add Item To List"))
        self.del_item_button.setText(_translate("MainWindow", "Delete Item"))
        self.clear_button.setText(_translate("MainWindow", "Clear List"))
        self.save_data.setText(_translate("MainWindow", "Save to Database"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
